package DataDriven::Framework::Generator::Docs;

use strict;
use warnings;
use Moo;
use Carp qw(croak);
use File::Path qw(make_path);
use File::Spec;

has model      => (is => 'ro', required => 1);
has output_dir => (is => 'ro', required => 1);

my $BEGIN_MARKER = '<!-- BEGIN GENERATED -->';
my $END_MARKER   = '<!-- END GENERATED -->';

sub generate {
    my ($self) = @_;
    my $model = $self->model;
    make_path($self->output_dir);

    my @files_written;

    # Index page
    push @files_written, $self->_write_file('index.md', $self->_index_page($model));

    # Per-class pages
    for my $class ($model->classes) {
        next if $class->abstract;
        my $filename = lc($class->name) . '.md';
        push @files_written, $self->_write_file($filename, $self->_class_page($class, $model));
    }

    return @files_written;
}

sub _write_file {
    my ($self, $filename, $new_generated) = @_;
    my $path = File::Spec->catfile($self->output_dir, $filename);

    my $content;
    if (-f $path) {
        # Preserve content outside the generated markers
        open my $fh, '<', $path or croak "Cannot read $path: $!";
        $content = do { local $/; <$fh> };
        close $fh;
        if ($content =~ /\Q$BEGIN_MARKER\E(.*?)\Q$END_MARKER\E/s) {
            $content =~ s/\Q$BEGIN_MARKER\E.*?\Q$END_MARKER\E/$BEGIN_MARKER\n$new_generated\n$END_MARKER/s;
        } else {
            # No markers: prepend the generated section with markers
            $content = "$BEGIN_MARKER\n$new_generated\n$END_MARKER\n\n$content";
        }
    } else {
        $content = "$BEGIN_MARKER\n$new_generated\n$END_MARKER\n";
    }

    open my $fh, '>', $path or croak "Cannot write $path: $!";
    print $fh $content;
    close $fh;
    return $path;
}

sub _index_page {
    my ($self, $model) = @_;
    my @lines;
    push @lines, "# Schema Documentation\n";
    push @lines, "> Schema version: `" . $model->schema_version . "`  \n";
    push @lines, "> " . ($model->description || '') . "\n" if $model->description;
    push @lines, "\n## Entities\n";

    for my $class ($model->classes_in_dependency_order) {
        next if $class->abstract;
        my $name = $class->name;
        my $label = $class->effective_label;
        my $desc = $class->description ? " — " . $class->description : '';
        push @lines, "- [**$label** (`$name`)](" . lc($name) . ".md)$desc";
    }

    push @lines, "\n## Enumerations\n";
    for my $enum ($model->enums) {
        my $vals = join(', ', @{$enum->values});
        push @lines, "- **" . $enum->name . "**: `$vals`";
        push @lines, "  " . $enum->description if $enum->description;
    }

    return join("\n", @lines);
}

sub _class_page {
    my ($self, $class, $model) = @_;
    my @lines;
    my $name  = $class->name;
    my $label = $class->effective_label;

    push @lines, "# $label (`$name`)\n";
    push @lines, $class->description if $class->description;
    push @lines, '';

    # Inheritance
    if ($class->has_parent) {
        my $parent = $class->is_a;
        push @lines, "**Inherits from:** [`$parent`](" . lc($parent) . ".md)\n";
    }

    push @lines, "**Table:** `" . $class->effective_table . "`\n";

    # Slots table
    push @lines, "## Fields\n";
    push @lines, "| Field | Type | Required | Default | Description |";
    push @lines, "|-------|------|----------|---------|-------------|";

    for my $slot (sort { $a->ui_order <=> $b->ui_order } @{$class->all_slots}) {
        my $type_label = $slot->type eq 'enum'
            ? "enum([" . ($slot->enum // '') . "](" . lc($slot->enum // '') . "_enum.md))"
            : "`" . $slot->type . "`";
        my $required = $slot->required  ? 'Yes' :
                       $slot->autogenerated ? 'Auto' : 'No';
        my $default  = defined($slot->default) ? "`" . $slot->default . "`" : '';
        $default     = '_autogenerated_' if $slot->autogenerated;
        my $desc     = $slot->description // '';
        $desc .= ' _(read-only)_' if $slot->read_only;
        $desc .= ' _(API read-only)_' if $slot->api_read_only;
        $desc .= ' _(hidden)_' if $slot->hidden;
        my $field_label = $slot->effective_label;
        push @lines, "| $field_label (`" . $slot->name . "`) | $type_label | $required | $default | $desc |";
    }

    # Validation rules
    my @has_rules = grep {
        defined($_->pattern) || defined($_->min) || defined($_->max)
    } @{$class->all_slots};

    if (@has_rules) {
        push @lines, "\n## Validation Rules\n";
        for my $slot (@has_rules) {
            my $sname = $slot->effective_label . " (`" . $slot->name . "`)";
            push @lines, "- **$sname**:";
            push @lines, "  - Pattern: `" . $slot->pattern . "`" if defined($slot->pattern);
            push @lines, "  - Min: `" . $slot->min . "`" if defined($slot->min);
            push @lines, "  - Max: `" . $slot->max . "`" if defined($slot->max);
        }
    }

    # Relationships
    if (@{$class->relationships}) {
        push @lines, "\n## Relationships\n";
        for my $rel (@{$class->relationships}) {
            my $target = $rel->target;
            my $kind   = $rel->kind;
            my $via    = $rel->via ? " (via `" . $rel->via . "`)" : '';
            my $thru   = $rel->through ? " through [`" . $rel->through . "`](" . lc($rel->through) . ".md)" : '';
            push @lines, "- **" . $rel->name . "** — *$kind* → [`$target`](" . lc($target) . ".md)$via$thru";
            push @lines, "  " . $rel->description if $rel->description;
        }
    }

    # Constraints
    my @unique = $class->unique_constraints;
    my @indexes = $class->index_constraints;
    if (@unique || @indexes) {
        push @lines, "\n## Constraints\n";
        for my $con (@unique) {
            push @lines, "- **Unique**: " . join(', ', map { "`$_`" } @{$con->columns});
        }
        for my $con (@indexes) {
            push @lines, "- **Index**: " . join(', ', map { "`$_`" } @{$con->columns});
        }
    }

    # Inheritance diagram (ASCII)
    if ($class->has_parent) {
        push @lines, "\n## Inheritance\n";
        push @lines, "```";
        $self->_append_inheritance_tree(\@lines, $class, $model, 0);
        push @lines, "```";
    }

    return join("\n", @lines);
}

sub _append_inheritance_tree {
    my ($self, $lines, $class, $model, $depth) = @_;
    my $indent = '  ' x $depth;
    push @$lines, "${indent}" . $class->name . ($class->abstract ? ' (abstract)' : '');
    for my $child ($model->classes) {
        next unless $child->has_parent && $child->is_a eq $class->name;
        $self->_append_inheritance_tree($lines, $child, $model, $depth + 1);
    }
}

1;

__END__

=head1 NAME

DataDriven::Framework::Generator::Docs - Generate Markdown documentation from a Model

=head1 SYNOPSIS

    use DataDriven::Framework::Generator::Docs;

    my $gen = DataDriven::Framework::Generator::Docs->new(
        model      => $model,
        output_dir => 'docs/schema',
    );
    my @files = $gen->generate;

=head1 DESCRIPTION

Generates Markdown documentation files from a L<DataDriven::Framework::Model>.
Produces an index page (C<index.md>) and one page per concrete class.

=head2 Regeneration Safety

Generated sections are wrapped in HTML comment markers:

    <!-- BEGIN GENERATED -->
    ... generated content ...
    <!-- END GENERATED -->

On regeneration, only the content within the markers is replaced. Content
outside the markers is preserved, allowing you to add custom sections.

=head1 METHODS

=over 4

=item C<generate()>

Generates documentation into C<output_dir>. Returns a list of file paths written.

=back

=cut
