package DataDriven::Framework::Generator::JSONSchema;

use strict;
use warnings;
use Moo;
use JSON::PP qw(encode_json);
use DataDriven::Framework::Model::ValueType;

has model => (is => 'ro', required => 1);

# Generate JSON Schema draft-07 definitions for all classes.
# Returns a hashref that can be serialized to JSON or YAML.
sub generate {
    my ($self) = @_;
    my $model = $self->model;

    my %definitions;

    # Enum definitions
    for my $enum ($model->enums) {
        $definitions{$enum->name} = {
            type  => 'string',
            enum  => $enum->values,
            ( $enum->description ? (description => $enum->description) : () ),
        };
    }

    # Class definitions
    for my $class ($model->classes) {
        next if $class->abstract;
        $definitions{$class->name} = $self->_class_schema($class, $model);
    }

    return {
        '$schema'     => 'http://json-schema.org/draft-07/schema#',
        '$id'         => 'schema.json',
        title         => $model->description || 'Generated Schema',
        definitions   => \%definitions,
    };
}

sub generate_json {
    my ($self) = @_;
    return encode_json($self->generate);
}

sub _class_schema {
    my ($self, $class, $model) = @_;

    my %properties;
    my @required;

    for my $slot (@{$class->all_slots}) {
        next if $slot->hidden;
        $properties{$slot->name} = $self->_slot_schema($slot, $model);
        push @required, $slot->name
            if $slot->required && !$slot->autogenerated;
    }

    my %schema = (
        type        => 'object',
        properties  => \%properties,
        ( @required ? (required => \@required) : () ),
        ( $class->description ? (description => $class->description) : () ),
        additionalProperties => 0,
    );

    return \%schema;
}

sub _slot_schema {
    my ($self, $slot, $model) = @_;

    my %schema;

    if ($slot->type eq 'enum' && $slot->enum_obj) {
        %schema = (
            type  => 'string',
            enum  => $slot->enum_obj->values,
        );
    } else {
        %schema = %{ DataDriven::Framework::Model::ValueType->json_schema_type($slot->type) };
    }

    $schema{description} = $slot->description if $slot->description;
    $schema{readOnly}     = JSON::PP::true      if $slot->read_only || $slot->autogenerated;
    $schema{default}      = $slot->default      if defined($slot->default) && !$slot->autogenerated;

    # Validation constraints
    if (defined($slot->min)) {
        if ($slot->type =~ /^(integer|float)$/) {
            $schema{minimum} = $slot->min + 0;
        } else {
            $schema{minLength} = $slot->min + 0;
        }
    }
    if (defined($slot->max)) {
        if ($slot->type =~ /^(integer|float)$/) {
            $schema{maximum} = $slot->max + 0;
        } else {
            $schema{maxLength} = $slot->max + 0;
        }
    }
    $schema{pattern} = $slot->pattern if defined($slot->pattern);

    return \%schema;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Generator::JSONSchema - Generate JSON Schema definitions from a Model

=head1 SYNOPSIS

    use DataDriven::Framework::Generator::JSONSchema;

    my $gen = DataDriven::Framework::Generator::JSONSchema->new(model => $model);

    # Returns a Perl data structure
    my $schema = $gen->generate;

    # Returns a JSON string
    my $json = $gen->generate_json;

=head1 DESCRIPTION

Generates JSON Schema (draft-07) from a L<DataDriven::Framework::Model>.

Each concrete class produces a C<definitions> entry with typed properties,
required fields, validation constraints (pattern, min/max), readOnly flags
for autogenerated/read_only fields, and enum references.

=head1 METHODS

=over 4

=item C<generate()>

Returns the complete JSON Schema as a Perl hashref.

=item C<generate_json()>

Returns the JSON Schema as a JSON string.

=back

=cut
