package DataDriven::Framework::Generator::SQL;

use strict;
use warnings;
use Moo;
use Carp qw(croak);
use DataDriven::Framework::Model::ValueType;

has model => (is => 'ro', required => 1);

# Generate complete MySQL DDL for the model.
# Returns a string of SQL.
sub generate {
    my ($self) = @_;
    my $model = $self->model;
    my @parts;

    push @parts, $self->_header($model);
    push @parts, $self->_framework_metadata_tables;

    # Generate tables in dependency order (parents before children)
    for my $class ($model->concrete_classes) {
        push @parts, $self->_class_to_sql($class, $model);
    }

    # Many-to-many join tables
    my %seen_join_tables;
    for my $class ($model->concrete_classes) {
        for my $rel (@{$class->relationships}) {
            next unless $rel->is_many_to_many;
            my $join_class = $model->class($rel->through) or next;
            next if $seen_join_tables{$join_class->effective_table}++;
            # Join table is handled by the class itself if it's concrete
        }
    }

    return join("\n\n", @parts) . "\n";
}

sub _header {
    my ($self, $model) = @_;
    return <<SQL;
-- ============================================================
-- Generated by DataDriven::Framework v${\ $model->framework_version}
-- Schema version: ${\ $model->schema_version}
-- Model hash: ${\ $model->model_hash}
-- ============================================================
-- DO NOT EDIT THIS FILE MANUALLY.
-- Regenerate with: ddframework generate-sql --schema <schema.yaml>
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SQL
}

sub _framework_metadata_tables {
    return <<'SQL';
-- Framework metadata tables
CREATE TABLE IF NOT EXISTS `_framework_schema_version` (
  `id`                INT          NOT NULL AUTO_INCREMENT,
  `schema_version`    VARCHAR(50)  NOT NULL,
  `framework_version` VARCHAR(50)  NOT NULL,
  `applied_at`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `model_hash`        VARCHAR(64)  NOT NULL,
  `notes`             TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `_framework_migrations` (
  `id`            INT          NOT NULL AUTO_INCREMENT,
  `from_version`  VARCHAR(50),
  `to_version`    VARCHAR(50)  NOT NULL,
  `applied_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `migration_sql` TEXT         NOT NULL,
  `checksum`      VARCHAR(64),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SQL
}

sub _class_to_sql {
    my ($self, $class, $model) = @_;
    my $table = $class->effective_table;
    my @columns;
    my @constraints;
    my @foreign_keys;

    # For joined-table inheritance: child table only contains its OWN slots + FK to parent PK
    my $is_child = $class->has_parent && $class->parent_class && !$class->parent_class->abstract;

    my @slots_to_emit;
    if ($is_child) {
        # Own slots only + implicit parent FK
        @slots_to_emit = @{$class->own_slots};
    } else {
        # All slots (for root or child-of-abstract)
        @slots_to_emit = @{$class->all_slots};
    }

    # PK for child table
    my $parent_pk_col;
    if ($is_child) {
        my $parent = $class->parent_class;
        my $parent_pk = $parent->pk_slot;
        $parent_pk_col = $parent_pk ? $parent_pk->name : 'id';
        my $parent_table = $parent->effective_table;
        push @columns, "  `$parent_pk_col` INT NOT NULL COMMENT 'FK to parent $parent_table'";
        push @constraints, "  PRIMARY KEY (`$parent_pk_col`)";
        push @foreign_keys, sprintf(
            "  CONSTRAINT `fk_%s_%s` FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`) ON DELETE CASCADE",
            $table, $parent_table, $parent_pk_col, $parent_table, $parent_pk_col
        );
    }

    for my $slot (@slots_to_emit) {
        push @columns, $self->_slot_to_column($slot, $model, $table);
    }

    # Explicit FK columns for belongs_to relationships
    my %fk_processed;
    for my $rel (@{$class->relationships}) {
        next unless $rel->is_belongs_to;
        next if $fk_processed{$rel->via}++;

        my $target_class = $model->class($rel->target) or next;
        my $target_table = $target_class->effective_table;
        my $target_pk    = $target_class->pk_slot;
        my $target_pk_col = $target_pk ? $target_pk->name : 'id';

        push @foreign_keys, sprintf(
            "  CONSTRAINT `fk_%s_%s_%s` FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`)",
            $table, $rel->via, $target_table, $rel->via, $target_table, $target_pk_col
        );
    }

    # Unique constraints
    for my $con ($class->unique_constraints) {
        my $con_name = $con->effective_name($table);
        push @constraints, sprintf("  UNIQUE KEY `%s` (%s)", $con_name, $con->column_list);
    }

    # Index constraints
    for my $con ($class->index_constraints) {
        my $con_name = $con->effective_name($table);
        push @constraints, sprintf("  INDEX `%s` (%s)", $con_name, $con->column_list);
    }

    my @all_defs = (@columns, @constraints, @foreign_keys);
    my $col_defs = join(",\n", @all_defs);

    my $comment = $class->description ? " COMMENT='" . _escape_sql($class->description) . "'" : '';

    my $label = $class->effective_label;
    return <<SQL;
-- Class: $label (${\ $class->name})
CREATE TABLE IF NOT EXISTS `$table` (
$col_defs
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4$comment;
SQL
}

sub _slot_to_column {
    my ($self, $slot, $model, $table) = @_;

    my $col  = $slot->name;
    my $type = $self->_mysql_type($slot, $model);
    my @parts = ("  `$col`", $type);

    if ($slot->autogenerated && $slot->type eq 'integer') {
        push @parts, 'NOT NULL AUTO_INCREMENT';
        # PRIMARY KEY added separately below
        return join(' ', @parts) . ",\n  PRIMARY KEY (`$col`)";
    }

    if ($slot->autogenerated && $slot->type eq 'datetime') {
        if ($col eq 'created_at') {
            push @parts, 'NOT NULL DEFAULT CURRENT_TIMESTAMP';
        } elsif ($col eq 'updated_at') {
            push @parts, 'NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP';
        } else {
            push @parts, 'NOT NULL DEFAULT CURRENT_TIMESTAMP';
        }
        return join(' ', @parts);
    }

    if ($slot->required && !$slot->autogenerated) {
        push @parts, 'NOT NULL';
    } else {
        push @parts, 'NULL';
    }

    if (defined($slot->default) && !$slot->autogenerated) {
        my $default = $slot->default;
        if ($slot->type =~ /^(integer|float)$/) {
            push @parts, "DEFAULT $default";
        } else {
            push @parts, "DEFAULT '" . _escape_sql($default) . "'";
        }
    }

    if ($slot->description) {
        push @parts, "COMMENT '" . _escape_sql($slot->description) . "'";
    }

    return join(' ', @parts);
}

sub _mysql_type {
    my ($self, $slot, $model) = @_;
    my $base = DataDriven::Framework::Model::ValueType->mysql_type($slot->type);

    if ($slot->type eq 'enum' && $slot->enum_obj) {
        return 'ENUM(' . $slot->enum_obj->mysql_enum_list . ')';
    }

    if ($slot->type eq 'string') {
        # If there's a max, use it
        if (defined($slot->max) && $slot->max <= 255) {
            return "VARCHAR(${\$slot->max})";
        }
        return 'VARCHAR(255)';
    }

    return $base;
}

sub _escape_sql {
    my ($str) = @_;
    $str =~ s/'/\\'/g;
    return $str;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Generator::SQL - Generate MySQL DDL from a canonical Model

=head1 SYNOPSIS

    use DataDriven::Framework::Generator::SQL;

    my $gen = DataDriven::Framework::Generator::SQL->new(model => $model);
    my $sql = $gen->generate;
    print $sql;
    # or
    open my $fh, '>', 'schema.sql' or die $!;
    print $fh $sql;

=head1 DESCRIPTION

Generates MySQL-compatible DDL from a L<DataDriven::Framework::Model>.

=head2 Inheritance Strategy

Uses I<joined-table inheritance>: each class in a hierarchy gets its own table.

=over 4

=item * Root (or child-of-abstract) classes get a full table with all their slots.

=item * Child classes get a table containing only their own additional slots, plus a
primary key column that is also a foreign key to the parent table's PK. The child
PK equals the parent PK.

=back

=head2 Framework Metadata Tables

Two tables are always generated:

=over 4

=item * C<_framework_schema_version> - records each time the schema is applied

=item * C<_framework_migrations> - records migration history

=back

=head1 METHODS

=over 4

=item C<generate()>

Returns the complete DDL as a string.

=back

=cut
