package DataDriven::Framework::Generator::UI;

use strict;
use warnings;
use Moo;
use Carp qw(croak);
use File::Path qw(make_path);
use File::Spec;
use JSON::PP qw(encode_json);

has model      => (is => 'ro', required => 1);
has output_dir => (is => 'ro', required => 1);

my $BEGIN_MARKER = '### BEGIN GENERATED ###';
my $END_MARKER   = '### END GENERATED ###';

sub generate {
    my ($self) = @_;
    my $model = $self->model;
    make_path($self->output_dir);

    my @files;

    # Generate UI JSON config for each class
    for my $class ($model->classes) {
        next if $class->abstract;
        my $base = lc($class->name);

        # JSON config
        my $config_file = File::Spec->catfile($self->output_dir, "${base}_ui.json");
        my $config = $self->_class_ui_config($class, $model);
        open my $fh, '>', $config_file or croak "Cannot write $config_file: $!";
        print $fh encode_json($config);
        close $fh;
        push @files, $config_file;

        # HTML scaffold
        my $html_file = File::Spec->catfile($self->output_dir, "${base}.html");
        push @files, $self->_write_html($html_file, $class, $model);
    }

    return @files;
}

sub _class_ui_config {
    my ($self, $class, $model) = @_;

    # List view: non-hidden fields, sorted by ui_order
    my @visible_slots = sort { $a->ui_order <=> $b->ui_order }
                        grep { !$_->hidden }
                        @{$class->all_slots};

    my @list_columns = map { {
        field   => $_->name,
        label   => $_->effective_label,
        type    => $_->type,
        sortable => ($_->type =~ /^(string|integer|float|date|datetime)$/ ? 1 : 0),
    } } @visible_slots;

    # Form view: writable fields only
    my @form_fields = map { $self->_slot_form_config($_, $model) }
                      grep { !$_->hidden && !$_->read_only && !$_->autogenerated }
                      @visible_slots;

    # Group form fields
    my %groups;
    for my $field (@form_fields) {
        my $group = $field->{group} // '';
        push @{$groups{$group}}, $field;
    }

    my @form_groups = map { {
        name   => $_ || 'General',
        fields => $groups{$_},
    } } sort keys %groups;

    # Relationship selectors
    my @selectors;
    for my $rel (@{$class->relationships}) {
        next unless $rel->is_belongs_to;
        push @selectors, {
            field  => $rel->via,
            label  => $rel->effective_label,
            target => $rel->target,
        };
    }

    return {
        class       => $class->name,
        label       => $class->effective_label,
        table       => $class->effective_table,
        description => $class->description,
        list  => { columns  => \@list_columns },
        form  => { groups   => \@form_groups },
        relations => \@selectors,
    };
}

sub _slot_form_config {
    my ($self, $slot, $model) = @_;
    my %field = (
        name         => $slot->name,
        label        => $slot->effective_label,
        type         => $slot->effective_control_type,
        required     => $slot->required ? 1 : 0,
        group        => $slot->ui_group || '',
        order        => $slot->ui_order,
        placeholder  => $slot->placeholder || '',
        api_read_only => $slot->api_read_only ? 1 : 0,
    );
    $field{default} = $slot->default if defined($slot->default);
    if ($slot->type eq 'enum' && $slot->enum_obj) {
        $field{options} = [
            map { { value => $_, label => ucfirst($_) } }
                @{$slot->enum_obj->values}
        ];
    }
    $field{min}     = $slot->min     if defined($slot->min);
    $field{max}     = $slot->max     if defined($slot->max);
    $field{pattern} = $slot->pattern if defined($slot->pattern);
    return \%field;
}

sub _write_html {
    my ($self, $path, $class, $model) = @_;

    my $generated = $self->_generate_html_body($class, $model);

    my $content;
    if (-f $path) {
        open my $fh, '<', $path or croak "Cannot read $path: $!";
        $content = do { local $/; <$fh> };
        close $fh;
        if ($content =~ /\Q$BEGIN_MARKER\E(.*?)\Q$END_MARKER\E/s) {
            $content =~ s/\Q$BEGIN_MARKER\E.*?\Q$END_MARKER\E/$BEGIN_MARKER\n$generated\n$END_MARKER/s;
        } else {
            $content = "$BEGIN_MARKER\n$generated\n$END_MARKER\n\n$content";
        }
    } else {
        $content = $self->_html_page($class, $generated);
    }

    open my $fh, '>', $path or croak "Cannot write $path: $!";
    print $fh $content;
    close $fh;
    return $path;
}

sub _html_page {
    my ($self, $class, $body) = @_;
    my $title = $class->effective_label;
    return <<HTML;
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$title</title>
<style>
body { font-family: sans-serif; max-width: 900px; margin: 2em auto; padding: 0 1em; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }
th { background: #f5f5f5; }
form { max-width: 600px; }
.field { margin-bottom: 1em; }
label { display: block; font-weight: bold; margin-bottom: 4px; }
input, select, textarea { width: 100%; padding: 6px; box-sizing: border-box; }
.required::after { content: ' *'; color: red; }
.btn { padding: 8px 16px; background: #0070f3; color: #fff; border: none; cursor: pointer; }
</style>
</head>
<body>
$BEGIN_MARKER
$body
$END_MARKER
</body>
</html>
HTML
}

sub _generate_html_body {
    my ($self, $class, $model) = @_;
    my $name  = $class->name;
    my $label = $class->effective_label;

    my @visible = sort { $a->ui_order <=> $b->ui_order }
                  grep { !$_->hidden } @{$class->all_slots};

    # List table
    my $headers = join('', map { "<th>" . $_->effective_label . "</th>" } @visible);
    my $row     = join('', map { "<td><!-- " . $_->name . " --></td>" } @visible);

    # Form fields
    my $form_fields = '';
    for my $slot (grep { !$_->read_only && !$_->autogenerated } @visible) {
        my $input = $self->_html_input($slot, $model);
        my $req   = $slot->required ? ' class="required"' : '';
        my $ph    = $slot->placeholder ? qq| placeholder="${\$slot->placeholder}"| : '';
        $form_fields .= <<HTML;
<div class="field">
  <label for="${\$slot->name}"$req>${\$slot->effective_label}</label>
  $input
</div>
HTML
    }

    return <<HTML;
<h1>$label</h1>
<h2>List</h2>
<table>
  <thead><tr>$headers<th>Actions</th></tr></thead>
  <tbody>
    <tr>$row<td><a href="#">Edit</a> | <a href="#">Delete</a></td></tr>
  </tbody>
</table>
<h2>Create / Edit</h2>
<form method="post">
$form_fields
<button type="submit" class="btn">Save</button>
</form>
HTML
}

sub _html_input {
    my ($self, $slot, $model) = @_;
    my $name = $slot->name;
    my $type = $slot->effective_control_type;

    if ($type eq 'textarea') {
        return qq|<textarea name="$name" id="$name"></textarea>|;
    }

    if ($type eq 'select' && $slot->enum_obj) {
        my $opts = join('', map { qq|<option value="$_">$_</option>| } @{$slot->enum_obj->values});
        return qq|<select name="$name" id="$name">$opts</select>|;
    }

    if ($type eq 'checkbox') {
        return qq|<input type="checkbox" name="$name" id="$name" value="1">|;
    }

    my $extra = '';
    $extra .= qq| min="${\$slot->min}"| if defined($slot->min) && $type eq 'number';
    $extra .= qq| max="${\$slot->max}"| if defined($slot->max) && $type eq 'number';
    $extra .= qq| pattern="${\$slot->pattern}"| if defined($slot->pattern);

    return qq|<input type="$type" name="$name" id="$name"$extra>|;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Generator::UI - Generate UI scaffold from a Model

=head1 SYNOPSIS

    use DataDriven::Framework::Generator::UI;

    my $gen = DataDriven::Framework::Generator::UI->new(
        model      => $model,
        output_dir => 'ui/generated',
    );
    my @files = $gen->generate;

=head1 DESCRIPTION

Generates two artifacts per concrete class:

=over 4

=item * B<JSON UI config> (C<classname_ui.json>) - renderer-agnostic description
of list view columns and form fields, including types, labels, groups, validation rules,
enum options, and relationship selectors.

=item * B<HTML scaffold> (C<classname.html>) - a simple self-contained HTML page
with a list table and create/edit form.

=back

=head2 Regeneration Safety

HTML files use C<### BEGIN GENERATED ###> / C<### END GENERATED ###> markers.
Content outside the markers is preserved on regeneration, allowing custom additions.

=head1 METHODS

=over 4

=item C<generate()>

Generates all UI files into C<output_dir>. Returns list of file paths.

=back

=cut
