package DataDriven::Framework::Runtime::ClassGenerator;

use strict;
use warnings;
use Moo;
use Carp qw(croak);

has registry => (is => 'ro', required => 1);
has namespace => (is => 'ro', default => sub { 'DataDriven::Generated' });

# Generate and load (into Perl symbol table) all classes in the model.
sub generate_all {
    my ($self) = @_;
    my $model = $self->registry->model;
    my %generated;
    for my $class ($model->classes_in_dependency_order) {
        next if $class->abstract;
        my $perl_class = $self->generate_class($class);
        $generated{$class->name} = $perl_class;
    }
    return %generated;
}

# Generate and eval a single Perl class for the given model class.
# Returns the Perl package name.
sub generate_class {
    my ($self, $model_class) = @_;
    my $pkg  = $self->namespace . '::' . $model_class->name;
    my $base = 'DataDriven::Framework::Runtime::Object';

    # Build accessor code
    my $accessors = '';
    for my $slot (@{$model_class->all_slots}) {
        my $name = $slot->name;
        $accessors .= $self->_accessor_code($name, $slot);
    }

    # Relationship accessors
    my $rel_accessors = '';
    for my $rel (@{$model_class->relationships}) {
        $rel_accessors .= $self->_rel_accessor_code($rel, $model_class);
    }

    my $code = <<PERL;
package $pkg;
use strict;
use warnings;
use parent '$base';

$accessors
$rel_accessors

1;
PERL

    # Eval the generated code
    {
        local $@;
        eval $code;
        croak "ClassGenerator: failed to generate $pkg:\n$@\n---\n$code" if $@;
    }

    # Register metadata
    $pkg->_register_meta($model_class, $self->registry);

    return $pkg;
}

sub _accessor_code {
    my ($self, $name, $slot) = @_;

    if ($slot->read_only || $slot->autogenerated) {
        # Read-only accessor
        return <<PERL;
sub $name { \$_[0]->{$name} }
PERL
    } else {
        # Read-write accessor
        return <<PERL;
sub $name {
    my \$self = shift;
    if (\@_) { \$self->{$name} = shift }
    return \$self->{$name};
}
PERL
    }
}

sub _rel_accessor_code {
    my ($self, $rel, $model_class) = @_;
    my $name   = $rel->name;
    my $target = $rel->target;
    my $ns     = $self->namespace;

    if ($rel->is_belongs_to) {
        my $via = $rel->via;
        return <<PERL;
sub $name {
    my (\$self, \$dbh) = \@_;
    \$dbh //= \$self->_registry->dbh;
    my \$id = \$self->{$via};
    return undef unless defined \$id;
    return '${ns}::${target}'->load(\$id, \$dbh);
}
PERL
    }

    if ($rel->is_has_many) {
        my $via = $rel->via // 'id';
        return <<PERL;
sub $name {
    my (\$self, \$dbh) = \@_;
    \$dbh //= \$self->_registry->dbh;
    my \$target_class = '${ns}::${target}';
    my \$mc    = \$target_class->_model_class;
    my \$table = \$mc->effective_table;
    my \@all_slots = \@{\$mc->all_slots};
    my \$cols = join(', ', map { "`\$_`" } map { \$_->name } \@all_slots);
    my \$pk   = \$self->_model_class->pk_slot;
    my \$pk_col = \$pk ? \$pk->name : 'id';
    my \$rows = \$dbh->selectall_arrayref(
        "SELECT \$cols FROM `\$table` WHERE `$via` = ?",
        { Slice => {} }, \$self->{\$pk_col}
    );
    return map { \$target_class->_from_row(\$_) } \@\$rows;
}
PERL
    }

    # many_to_many: navigate through the join class
    if ($rel->is_many_to_many) {
        my $through = $rel->through;
        return <<PERL;
sub $name {
    my (\$self, \$dbh) = \@_;
    \$dbh //= \$self->_registry->dbh;
    # many_to_many via join class '${ns}::${through}'
    my \$through_class = '${ns}::${through}';
    my \@through = \$through_class->load_all(\$dbh);
    return \@through;
}
PERL
    }

    return '';
}

1;

__END__

=head1 NAME

DataDriven::Framework::Runtime::ClassGenerator - Dynamically generate Perl classes from a Model

=head1 SYNOPSIS

    use DataDriven::Framework::Runtime::ClassGenerator;

    my $gen = DataDriven::Framework::Runtime::ClassGenerator->new(
        registry  => $registry,
        namespace => 'MyApp::Model',
    );
    my %classes = $gen->generate_all;

    my $User = $classes{User};  # MyApp::Model::User package name
    my $u = $User->new(username => 'alice');

=head1 DESCRIPTION

Generates Perl packages dynamically (using string C<eval>) for each concrete
class in the model. Generated packages inherit from
L<DataDriven::Framework::Runtime::Object> and have:

=over 4

=item * Typed accessors for all slots (read-only for C<read_only>/C<autogenerated>)

=item * C<belongs_to> relationship accessors (returns an object)

=item * C<has_many> relationship accessors (returns a list of objects)

=back

Generated classes are loaded into the Perl symbol table under the configured
C<namespace>.

=head1 METHODS

=over 4

=item C<generate_all()>

Generates all non-abstract classes. Returns a hash of model class name ->
Perl package name.

=item C<generate_class($model_class)>

Generates a single class. Returns the Perl package name.

=back

=cut
