package DataDriven::Framework::Runtime::Object;

use strict;
use warnings;
use Carp qw(croak confess);
use Scalar::Util qw(blessed);

# Base class for all generated runtime objects.
# Subclasses are dynamically generated by ClassGenerator.

my %_class_meta;   # class_name -> { model_class => ..., registry => ... }

sub _register_meta {
    my ($class, $model_class, $registry) = @_;
    $_class_meta{$class} = { model_class => $model_class, registry => $registry };
}

sub _meta {
    my ($self_or_class) = @_;
    my $class = blessed($self_or_class) // $self_or_class;
    my $meta = $_class_meta{$class};
    croak "No metadata registered for class '$class'" unless defined $meta;
    return $meta;
}

sub _model_class {
    my ($self_or_class) = @_;
    return $self_or_class->_meta->{model_class};
}

sub _registry {
    my ($self_or_class) = @_;
    return $self_or_class->_meta->{registry};
}

# Constructor: new(field => value, ...)
sub new {
    my ($class, %args) = @_;
    my $self = bless {}, $class;
    my $mc   = $self->_model_class;

    for my $slot (@{$mc->all_slots}) {
        my $name = $slot->name;
        if (exists $args{$name}) {
            $self->{$name} = $args{$name};
        } elsif (defined $slot->default && !$slot->autogenerated) {
            $self->{$name} = $slot->default;
        } else {
            $self->{$name} = undef;
        }
    }

    # Store any extra keys (may include unparsed fields)
    $self->{_extra} = {};

    return $self;
}

# Load by primary key from database
sub load {
    my ($class, $id, $dbh) = @_;
    $dbh //= $class->_registry->dbh
        or croak "load: no dbh provided and registry has no dbh";

    my $mc    = $class->_model_class;
    my $table = $mc->effective_table;
    my $pk    = $mc->pk_slot or croak "Class has no primary key slot";
    my $pk_col = $pk->name;

    # For inheritance: may need to join parent table
    my @all_slots = @{$mc->all_slots};
    my @cols = map { "`$_`" } map { $_->name } @all_slots;

    # If class has parent, join
    my $sql;
    if ($mc->has_parent && $mc->parent_class && !$mc->parent_class->abstract) {
        my $parent_table = $mc->parent_class->effective_table;
        my $parent_cols = join(', ', map { "p.`$_`" } map { $_->name } @{$mc->parent_class->all_slots});
        my $own_cols    = join(', ', map { "c.`$_`" } map { $_->name } @{$mc->own_slots});
        my $sel = join(', ', grep { $_ } $parent_cols, $own_cols);
        $sql = "SELECT $sel FROM `$parent_table` p"
             . " JOIN `$table` c ON c.`$pk_col` = p.`$pk_col`"
             . " WHERE p.`$pk_col` = ?";
    } else {
        my $cols_str = join(', ', map { "`$_`" } map { $_->name } @all_slots);
        $sql = "SELECT $cols_str FROM `$table` WHERE `$pk_col` = ?";
    }

    my $row = $dbh->selectrow_hashref($sql, {}, $id);
    return undef unless $row;

    return $class->_from_row($row);
}

# Load all rows (simple, no pagination)
sub load_all {
    my ($class, $dbh, %opts) = @_;
    $dbh //= $class->_registry->dbh;
    my $mc    = $class->_model_class;
    my $table = $mc->effective_table;
    my @all_slots = @{$mc->all_slots};
    my $cols_str = join(', ', map { "`$_`" } map { $_->name } @all_slots);
    my $limit = $opts{limit} ? " LIMIT " . int($opts{limit}) : '';
    my $rows = $dbh->selectall_arrayref(
        "SELECT $cols_str FROM `$table`$limit",
        { Slice => {} }
    );
    return map { $class->_from_row($_) } @$rows;
}

sub _from_row {
    my ($class, $row) = @_;
    my $self = bless {}, $class;
    my $mc   = $class->_model_class;
    for my $slot (@{$mc->all_slots}) {
        $self->{$slot->name} = $row->{$slot->name};
    }
    $self->{_extra} = {};
    $self->{_is_persisted} = 1;
    return $self;
}

# Save (INSERT or UPDATE)
sub save {
    my ($self, $dbh) = @_;
    $dbh //= $self->_registry->dbh
        or croak "save: no dbh provided";

    my $mc    = $self->_model_class;
    my $table = $mc->effective_table;
    my $pk    = $mc->pk_slot;
    my $pk_col = $pk ? $pk->name : undef;

    # Collect writable columns (not autogenerated)
    my @writable = grep { !$_->autogenerated } @{$mc->own_slots};
    my @cols = map { $_->name } @writable;
    my @vals = map { $self->{$_->name} } @writable;

    if ($self->{_is_persisted} && $pk_col && defined $self->{$pk_col}) {
        # UPDATE
        my $set = join(', ', map { "`$_` = ?" } @cols);
        $dbh->do("UPDATE `$table` SET $set WHERE `$pk_col` = ?", {}, @vals, $self->{$pk_col});

        # If has parent, update parent table too
        if ($mc->has_parent && $mc->parent_class && !$mc->parent_class->abstract) {
            my $parent_mc    = $mc->parent_class;
            my $parent_table = $parent_mc->effective_table;
            my @parent_writable = grep { !$_->autogenerated } @{$parent_mc->own_slots};
            my @pcols = map { $_->name } @parent_writable;
            my @pvals = map { $self->{$_->name} } @parent_writable;
            if (@pcols) {
                my $pset = join(', ', map { "`$_` = ?" } @pcols);
                $dbh->do("UPDATE `$parent_table` SET $pset WHERE `$pk_col` = ?",
                         {}, @pvals, $self->{$pk_col});
            }
        }
    } else {
        # INSERT
        if ($mc->has_parent && $mc->parent_class && !$mc->parent_class->abstract) {
            # Insert into parent first
            my $parent_mc    = $mc->parent_class;
            my $parent_table = $parent_mc->effective_table;
            my @parent_writable = grep { !$_->autogenerated } @{$parent_mc->own_slots};
            my @pcols = map { $_->name } @parent_writable;
            my @pvals = map { $self->{$_->name} } @parent_writable;
            if (@pcols) {
                my $pcol_list = join(', ', map { "`$_`" } @pcols);
                my $pph_list  = join(', ', ('?') x @pvals);
                $dbh->do("INSERT INTO `$parent_table` ($pcol_list) VALUES ($pph_list)", {}, @pvals);
            } else {
                $dbh->do("INSERT INTO `$parent_table` () VALUES ()");
            }
            my $new_id = $dbh->last_insert_id(undef, undef, $parent_table, undef);
            $self->{$pk_col} = $new_id if $pk_col;

            # Insert into child table
            if (@cols) {
                my $col_list = join(', ', "`$pk_col`", map { "`$_`" } @cols);
                my $ph_list  = join(', ', ('?') x (1 + @vals));
                $dbh->do("INSERT INTO `$table` ($col_list) VALUES ($ph_list)",
                         {}, $self->{$pk_col}, @vals);
            } else {
                $dbh->do("INSERT INTO `$table` (`$pk_col`) VALUES (?)",
                         {}, $self->{$pk_col});
            }
        } else {
            # Simple insert
            if (@cols) {
                my $col_list = join(', ', map { "`$_`" } @cols);
                my $ph_list  = join(', ', ('?') x @vals);
                $dbh->do("INSERT INTO `$table` ($col_list) VALUES ($ph_list)", {}, @vals);
            } else {
                $dbh->do("INSERT INTO `$table` () VALUES ()");
            }
            if ($pk_col) {
                $self->{$pk_col} = $dbh->last_insert_id(undef, undef, $table, undef);
            }
        }
        $self->{_is_persisted} = 1;
    }

    return $self;
}

# Delete from database
sub delete {
    my ($self, $dbh) = @_;
    $dbh //= $self->_registry->dbh;
    my $mc    = $self->_model_class;
    my $table = $mc->effective_table;
    my $pk    = $mc->pk_slot or croak "delete: no primary key";
    my $pk_col = $pk->name;
    my $id    = $self->{$pk_col} or croak "delete: object has no ID";

    # Due to FK CASCADE, deleting from parent table should cascade
    if ($mc->has_parent && $mc->parent_class && !$mc->parent_class->abstract) {
        my $parent_table = $mc->parent_class->effective_table;
        $dbh->do("DELETE FROM `$parent_table` WHERE `$pk_col` = ?", {}, $id);
    } else {
        $dbh->do("DELETE FROM `$table` WHERE `$pk_col` = ?", {}, $id);
    }
    $self->{_is_persisted} = 0;
    $self->{$pk_col} = undef;
    return $self;
}

# to_hashref: returns a plain hash of all slot values
sub to_hashref {
    my ($self) = @_;
    my $mc = $self->_model_class;
    my %h;
    for my $slot (@{$mc->all_slots}) {
        next if $slot->hidden;
        $h{$slot->name} = $self->{$slot->name};
    }
    return \%h;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Runtime::Object - Base class for generated runtime objects

=head1 SYNOPSIS

    # Usually you don't use this directly; use Registry to get generated classes.
    my $User = $registry->class('User');
    my $u = $User->new(username => 'alice');
    $u->save($dbh);

    my $loaded = $User->load(1, $dbh);
    print $loaded->username;

=head1 DESCRIPTION

All classes generated by L<DataDriven::Framework::Runtime::ClassGenerator> inherit
from C<DataDriven::Framework::Runtime::Object>. This base class provides:

=over 4

=item * C<new(%args)> - Constructor with defaults

=item * C<load($id, $dbh)> - Load by primary key

=item * C<load_all($dbh, %opts)> - Load all rows

=item * C<save($dbh)> - INSERT or UPDATE

=item * C<delete($dbh)> - DELETE

=item * C<to_hashref()> - Serialize to plain hash

=back

Typed accessors for each slot are added by the ClassGenerator.

=cut
