package DataDriven::Framework;

use strict;
use warnings;

our $VERSION = '0.01';

1;

__END__

=head1 NAME

DataDriven::Framework - Schema-first, data-driven application development for Perl

=head1 VERSION

0.01

=head1 SYNOPSIS

    use DataDriven::Framework::Schema::Parser;
    use DataDriven::Framework::Generator::SQL;

    my $parser = DataDriven::Framework::Schema::Parser->new;
    my $model  = $parser->parse('schema/myapp.yaml');

    my $gen = DataDriven::Framework::Generator::SQL->new(model => $model);
    print $gen->generate;

=head1 DESCRIPTION

DataDriven::Framework is a Perl framework for schema-first, data-driven application
development. The central idea is that a single YAML data model file is the canonical
source of truth for your application. From that single source, the framework can
generate and keep in sync:

=over 4

=item * MySQL DDL (CREATE TABLE statements, foreign keys, indexes)

=item * OpenAPI 3.0 specifications

=item * JSON Schema definitions

=item * Admin UI scaffolding (JSON config + HTML forms)

=item * Project documentation (Markdown)

=item * SQL migration patches between schema versions

=item * Perl runtime model classes for data access

=item * Test sandbox utilities for isolated testing

=back

=head1 ARCHITECTURE

The framework is organized into several layers:

    YAML Schema Files
         |
    Schema::Parser  -->  Schema::Validator  -->  Schema::Resolver
         |
    DataDriven::Framework::Model (canonical internal model)
         |
    +----+----+--------+--------+-----+----------+
    |    |    |        |        |     |          |
   SQL OpenAPI JSON   UI     Docs  Runtime   Sandbox
   Gen  Gen   Schema  Gen    Gen   Layer     Utilities
              Gen

=head2 Internal Model

The canonical model lives in L<DataDriven::Framework::Model> and its subordinate
classes. It is a pure in-memory representation of the schema, independent of any
serialization format or output target.

=head2 Schema Layer

L<DataDriven::Framework::Schema::Parser> reads one or more YAML files and builds
the canonical model. L<DataDriven::Framework::Schema::Validator> validates the
semantics of the model. L<DataDriven::Framework::Schema::Resolver> flattens
inheritance hierarchies and resolves cross-file references.

=head2 Generator Layer

Each generator in C<DataDriven::Framework::Generator::*> takes a canonical model
and produces an artifact. Generators are stateless and deterministic; the same
model always produces the same output.

=head2 Runtime Layer

L<DataDriven::Framework::Runtime::Registry> loads a schema and dynamically
generates Perl classes at runtime. Generated classes inherit from
L<DataDriven::Framework::Runtime::Object> and provide typed accessors, CRUD
methods, and relationship navigation.

=head2 Sandbox Layer

L<DataDriven::Framework::Sandbox::Environment> provides test utilities: stand up
a temporary database, apply schema, load fixtures, run tests, then tear down.

=head1 YAML SCHEMA FORMAT

A schema file is a YAML document with the following top-level keys:

=over 4

=item C<schema_version> (string, required)

The semantic version of your data model. Increment this when you make schema
changes to enable the migration engine to produce diffs.

=item C<framework_version> (string, optional)

Minimum framework version required to process this schema.

=item C<description> (string, optional)

Human-readable description of the schema.

=item C<enums> (hash, optional)

Named enumeration definitions. Each key is the enum name; the value has:

    enums:
      Status:
        values: [active, inactive, deleted]
        default: active
        description: "Lifecycle status"

=item C<classes> (hash, required)

Entity definitions. Each key is the class name. Class attributes:

=over 4

=item C<label> - Human-readable name

=item C<description> - Documentation string

=item C<table> - Override the auto-generated table name (default: snake_case plural of class name)

=item C<abstract> - If true, no table is generated; only used as a parent

=item C<is_a> - Parent class name for single inheritance

=item C<slots> - Array of field definitions (see below)

=item C<relationships> - Hash with C<belongs_to>, C<has_many>, C<many_to_many>

=item C<constraints> - Hash with C<unique> (array of field names or arrays of names for composite)

=back

=back

B<Slot attributes:>

    - name: field_name        # required
      type: string            # required: string|integer|float|boolean|date|datetime|text|enum
      enum: EnumName          # required when type=enum
      required: true/false
      default: value
      autogenerated: true/false   # ID/timestamps - set by DB
      read_only: true/false       # never writable via API or forms
      api_read_only: true/false   # readable in API but not writable
      hidden: true/false          # excluded from UI and API output
      label: "Human Label"
      description: "Documentation"
      placeholder: "Enter value..."
      control_type: text|textarea|select|checkbox|date|datetime|number
      ui_order: 1
      ui_group: "Basic Info"
      min: 0
      max: 100
      pattern: '^\d+$'

=head1 QUICKSTART

=head2 1. Create a schema file

    # schema/myapp.yaml
    schema_version: "1.0.0"

    enums:
      Status:
        values: [active, inactive]
        default: active

    classes:
      User:
        label: User
        slots:
          - name: id
            type: integer
            autogenerated: true
            read_only: true
            required: true
          - name: username
            type: string
            required: true
            label: Username
          - name: status
            type: enum
            enum: Status
            default: active
        constraints:
          unique: [username]

=head2 2. Validate the schema

    ddframework validate --schema schema/myapp.yaml

=head2 3. Generate SQL

    ddframework generate-sql --schema schema/myapp.yaml --output schema.sql

=head2 4. Generate OpenAPI spec

    ddframework generate-openapi --schema schema/myapp.yaml --output openapi.yaml

=head2 5. Use in tests

    use DataDriven::Framework::Sandbox::TestHelper qw(with_sandbox);

    with_sandbox('schema/myapp.yaml', sub {
        my ($env) = @_;
        my $User = $env->registry->class('User');
        my $u = $User->new(username => 'alice', status => 'active');
        $u->save($env->dbh);
        is($u->id, 1, 'got ID after save');
    });

=head1 CLI USAGE

    ddframework <command> [options]

    Commands:
      validate          Validate a schema file
      generate-sql      Generate MySQL DDL
      reverse-from-db   Generate YAML schema from existing database
      generate-openapi  Generate OpenAPI 3.0 spec
      generate-json-schema  Generate JSON Schema definitions
      generate-ui       Generate UI scaffold
      generate-docs     Generate Markdown documentation
      diff              Compare two schema versions
      migrate           Apply a migration SQL file
      init-project      Initialize a new project skeleton
      version           Show version information

    Run: ddframework help <command> for details.

=head1 LIMITATIONS AND FUTURE IMPROVEMENTS

=over 4

=item * Currently only MySQL is supported as a database backend. PostgreSQL support
is planned.

=item * Inheritance uses the joined-table strategy only. Single-table inheritance
is not yet supported.

=item * The UI generator produces a JSON config and simple HTML scaffold. Integration
with modern JS frameworks (React, Vue) is planned.

=item * The reverse generator performs best-effort type mapping; complex MySQL types
may need manual review.

=item * Conditional validation rules in YAML are parsed but not fully enforced at
the runtime layer yet.

=item * Many-to-many navigation is read-only in the current runtime layer.

=back

=head1 AUTHOR

TimeOfMind Project

=head1 LICENSE

This library is free software. You can redistribute it and/or modify it under
the same terms as Perl itself.

=cut
