package DataDriven::Framework::Model::Class;

use strict;
use warnings;
use Moo;
use Carp qw(croak);
use List::Util qw(first);

has name          => (is => 'ro', required => 1);
has label         => (is => 'ro', default  => sub { undef });
has description   => (is => 'ro', default  => sub { '' });
has table         => (is => 'rw', default  => sub { undef });   # rw: resolver sets it
has abstract      => (is => 'ro', default  => sub { 0 });
has is_a          => (is => 'ro', default  => sub { undef });   # parent class name
has slots         => (is => 'ro', default  => sub { [] });      # arrayref of Slot objects
has relationships => (is => 'ro', default  => sub { [] });      # arrayref of Relationship objects
has constraints   => (is => 'ro', default  => sub { [] });      # arrayref of Constraint objects

# Resolved parent Class object (set by resolver)
has parent_class  => (is => 'rw', default  => sub { undef });

# All slots including inherited ones (set by resolver)
has resolved_slots => (is => 'rw', default => sub { undef });

sub effective_label {
    my ($self) = @_;
    return $self->label if defined($self->label) && length($self->label);
    (my $label = $self->name) =~ s/([A-Z])/ $1/g;
    $label =~ s/^\s+//;
    return $label;
}

# Auto-derive table name: MyClassName -> my_class_names (snake_case plural)
sub effective_table {
    my ($self) = @_;
    return $self->table if defined($self->table) && length($self->table);
    my $name = $self->name;
    $name =~ s/([A-Z])/'_'.lc($1)/ge;
    $name =~ s/^_//;
    # Simple pluralisation
    if ($name =~ /s$/) {
        $name .= 'es';
    } elsif ($name =~ /[^aeiou]y$/) {
        $name =~ s/y$/ies/;
    } else {
        $name .= 's';
    }
    return $name;
}

sub slot {
    my ($self, $name) = @_;
    return first { $_->name eq $name } @{$self->slots};
}

sub has_slot {
    my ($self, $name) = @_;
    return defined($self->slot($name));
}

sub relationship {
    my ($self, $name) = @_;
    return first { $_->name eq $name } @{$self->relationships};
}

sub add_slot {
    my ($self, $slot) = @_;
    croak "Class '" . $self->name . "': duplicate slot '" . $slot->name . "'"
        if $self->has_slot($slot->name);
    push @{$self->slots}, $slot;
}

sub add_relationship {
    my ($self, $rel) = @_;
    push @{$self->relationships}, $rel;
}

sub add_constraint {
    my ($self, $con) = @_;
    push @{$self->constraints}, $con;
}

sub all_slots {
    my ($self) = @_;
    return $self->resolved_slots // $self->slots;
}

sub own_slots {
    my ($self) = @_;
    return $self->slots;
}

sub pk_slot {
    my ($self) = @_;
    return first { $_->autogenerated && $_->type eq 'integer' } @{$self->all_slots};
}

sub unique_constraints {
    my ($self) = @_;
    return grep { $_->is_unique } @{$self->constraints};
}

sub index_constraints {
    my ($self) = @_;
    return grep { $_->is_index } @{$self->constraints};
}

sub has_parent {
    my ($self) = @_;
    return defined($self->is_a);
}

sub to_hashref {
    my ($self) = @_;
    my %h = (
        name  => $self->name,
        slots => [map { $_->to_hashref } @{$self->slots}],
    );
    $h{label}         = $self->label       if defined $self->label;
    $h{description}   = $self->description if $self->description;
    $h{table}         = $self->table       if defined $self->table;
    $h{abstract}      = 1                  if $self->abstract;
    $h{is_a}          = $self->is_a        if defined $self->is_a;
    $h{relationships} = [map { $_->to_hashref } @{$self->relationships}]
        if @{$self->relationships};
    return \%h;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Model::Class - Represents a single entity/class in the data model

=head1 SYNOPSIS

    my $class = DataDriven::Framework::Model::Class->new(
        name  => 'Device',
        label => 'Device',
        slots => [$id_slot, $hostname_slot],
    );

    my $slot = $class->slot('hostname');
    my $table = $class->effective_table;   # 'devices'

=head1 ATTRIBUTES

=over 4

=item C<name> (required) - Class name (PascalCase recommended)

=item C<label> - Human-readable name

=item C<description> - Documentation string

=item C<table> - Override auto-generated table name

=item C<abstract> - If true, no table is generated

=item C<is_a> - Parent class name

=item C<slots> - Arrayref of L<DataDriven::Framework::Model::Slot> objects

=item C<relationships> - Arrayref of L<DataDriven::Framework::Model::Relationship> objects

=item C<constraints> - Arrayref of L<DataDriven::Framework::Model::Constraint> objects

=back

=head1 METHODS

=over 4

=item C<effective_label()>

Returns label or auto-generates from class name.

=item C<effective_table()>

Returns table name or auto-generates as snake_case plural.

=item C<slot($name)>

Returns the named Slot or undef.

=item C<pk_slot()>

Returns the primary key (autogenerated integer) slot, or undef.

=item C<all_slots()>

Returns all slots including inherited ones (after resolver runs).

=item C<own_slots()>

Returns only slots directly defined on this class.

=back

=cut
