package DataDriven::Framework::Model::Slot;

use strict;
use warnings;
use Moo;
use Carp qw(croak);
use DataDriven::Framework::Model::ValueType;

has name          => (is => 'ro', required => 1);
has type          => (is => 'ro', required => 1);
has enum          => (is => 'ro', default  => sub { undef });  # enum name for type=enum
has required      => (is => 'ro', default  => sub { 0 });
has default       => (is => 'ro', default  => sub { undef });
has autogenerated => (is => 'ro', default  => sub { 0 });
has read_only     => (is => 'ro', default  => sub { 0 });
has api_read_only => (is => 'ro', default  => sub { 0 });
has hidden        => (is => 'ro', default  => sub { 0 });

# UI metadata
has label         => (is => 'ro', default  => sub { undef });
has description   => (is => 'ro', default  => sub { '' });
has placeholder   => (is => 'ro', default  => sub { '' });
has control_type  => (is => 'ro', default  => sub { undef });  # overrides auto-detection
has ui_order      => (is => 'ro', default  => sub { 999 });
has ui_group      => (is => 'ro', default  => sub { '' });

# Validation metadata
has min           => (is => 'ro', default  => sub { undef });
has max           => (is => 'ro', default  => sub { undef });
has pattern       => (is => 'ro', default  => sub { undef });

# Resolved enum object (set by resolver, not by parser directly)
has enum_obj      => (is => 'rw', default  => sub { undef });

# The class name this slot was defined in (may differ from owning class due to inheritance)
has defined_in    => (is => 'rw', default  => sub { undef });

sub BUILD {
    my ($self) = @_;
    croak "Slot '" . $self->name . "': unknown type '" . $self->type . "'"
        unless DataDriven::Framework::Model::ValueType->is_valid($self->type);
    croak "Slot '" . $self->name . "': type=enum requires 'enum' attribute"
        if $self->type eq 'enum' && !defined($self->enum);
}

sub effective_label {
    my ($self) = @_;
    return $self->label if defined($self->label) && length($self->label);
    # Auto-generate from name: snake_case -> Title Case
    (my $label = $self->name) =~ s/_/ /g;
    $label =~ s/\b(\w)/uc($1)/ge;
    return $label;
}

sub effective_control_type {
    my ($self) = @_;
    return $self->control_type if defined $self->control_type;
    return DataDriven::Framework::Model::ValueType->html_input_type($self->type);
}

sub is_nullable {
    my ($self) = @_;
    return !$self->required && !$self->autogenerated;
}

sub to_hashref {
    my ($self) = @_;
    my %h = (
        name          => $self->name,
        type          => $self->type,
        required      => $self->required      ? 1 : 0,
        autogenerated => $self->autogenerated ? 1 : 0,
        read_only     => $self->read_only     ? 1 : 0,
        api_read_only => $self->api_read_only ? 1 : 0,
        hidden        => $self->hidden        ? 1 : 0,
        ui_order      => $self->ui_order,
    );
    $h{enum}        = $self->enum        if defined $self->enum;
    $h{default}     = $self->default     if defined $self->default;
    $h{label}       = $self->label       if defined $self->label;
    $h{description} = $self->description if $self->description;
    $h{placeholder} = $self->placeholder if $self->placeholder;
    $h{control_type}= $self->control_type if defined $self->control_type;
    $h{ui_group}    = $self->ui_group    if $self->ui_group;
    $h{min}         = $self->min         if defined $self->min;
    $h{max}         = $self->max         if defined $self->max;
    $h{pattern}     = $self->pattern     if defined $self->pattern;
    return \%h;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Model::Slot - Represents a field/slot in a model class

=head1 SYNOPSIS

    my $slot = DataDriven::Framework::Model::Slot->new(
        name      => 'username',
        type      => 'string',
        required  => 1,
        label     => 'Username',
        ui_order  => 2,
        pattern   => '^[a-z0-9_]+$',
    );

=head1 ATTRIBUTES

=over 4

=item C<name> (required) - Field name (snake_case recommended)

=item C<type> (required) - Primitive type: string|integer|float|boolean|date|datetime|text|enum

=item C<enum> - Enum name (required when type=enum)

=item C<required> - Boolean; field must be present and non-null

=item C<default> - Default value

=item C<autogenerated> - Set by the database (e.g., AUTO_INCREMENT, DEFAULT NOW())

=item C<read_only> - Never writable via API or forms

=item C<api_read_only> - Readable but not writable via API

=item C<hidden> - Excluded from UI and API output

=item C<label> - Human-readable label

=item C<description> - Documentation string

=item C<placeholder> - Input placeholder text

=item C<control_type> - Override HTML input type

=item C<ui_order> - Sort order in forms (lower = earlier)

=item C<ui_group> - Logical group name for fieldset rendering

=item C<min> - Minimum numeric value or string length

=item C<max> - Maximum numeric value or string length

=item C<pattern> - Regex pattern for validation

=back

=head1 METHODS

=over 4

=item C<effective_label()>

Returns C<label> or auto-generates one from the field name.

=item C<effective_control_type()>

Returns C<control_type> or derives it from the field type.

=item C<is_nullable()>

Returns true if the field may be NULL in the database.

=item C<to_hashref()>

Returns a plain hashref representation suitable for serialization.

=back

=cut
