package TestUtils;

use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(simple_schema_yaml device_schema_yaml);

sub simple_schema_yaml {
    return \<<'YAML';
schema_version: "1.0.0"
framework_version: "0.01"
description: "Simple test schema"

enums:
  Status:
    values: [active, inactive, deleted]
    default: active

classes:
  User:
    label: User
    description: "A user account"
    table: users
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: username
        type: string
        required: true
        label: Username
        pattern: '^[a-z0-9_]+$'
        ui_order: 1
      - name: email
        type: string
        required: true
        label: Email
        ui_order: 2
      - name: status
        type: enum
        enum: Status
        default: active
        ui_order: 3
      - name: created_at
        type: datetime
        autogenerated: true
        read_only: true
    constraints:
      unique: [username]

  Post:
    label: Post
    description: "A blog post"
    table: posts
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: title
        type: string
        required: true
        label: Title
        max: 255
        ui_order: 1
      - name: body
        type: text
        label: Body
        control_type: textarea
        ui_order: 2
      - name: user_id
        type: integer
        required: true
        hidden: true
      - name: created_at
        type: datetime
        autogenerated: true
        read_only: true
    relationships:
      belongs_to:
        - target: User
          via: user_id
          label: Author
YAML
}

sub device_schema_yaml {
    my $path = 'examples/device_management/schema/device.yaml';
    return $path if -f $path;
    # Try relative to script dir
    require FindBin;
    return "$FindBin::Bin/../examples/device_management/schema/device.yaml";
}

1;
