package DataDriven::Framework::Schema::Validator;

use strict;
use warnings;
use Moo;
use Carp qw(croak);

# Validate a Model's semantic correctness.
# Returns a list of error strings. Empty list = valid.

sub validate {
    my ($self, $model) = @_;
    my @errors;

    # 1. Validate each enum
    for my $enum ($model->enums) {
        push @errors, $self->_validate_enum($enum, $model);
    }

    # 2. Validate each class
    for my $class ($model->classes) {
        push @errors, $self->_validate_class($class, $model);
    }

    # 3. Check for inheritance cycles
    push @errors, $self->_check_inheritance_cycles($model);

    return @errors;
}

# Convenience: validate and die if there are errors
sub validate_or_die {
    my ($self, $model) = @_;
    my @errors = $self->validate($model);
    if (@errors) {
        croak "Schema validation failed:\n" . join("\n", map { "  - $_" } @errors);
    }
}

sub _validate_enum {
    my ($self, $enum, $model) = @_;
    my @errors;
    # Enum values must be non-empty strings
    for my $val (@{$enum->values}) {
        push @errors, "Enum '" . $enum->name . "': value must be a non-empty string"
            unless defined($val) && length($val);
    }
    return @errors;
}

sub _validate_class {
    my ($self, $class, $model) = @_;
    my @errors;
    my $cname = $class->name;

    # Inheritance target must exist
    if ($class->has_parent) {
        unless ($model->has_class($class->is_a)) {
            push @errors, "Class '$cname': parent class '" . $class->is_a . "' is not defined";
        }
    }

    # Validate slots
    my %seen_slot_names;
    for my $slot (@{$class->slots}) {
        my $sname = $slot->name;

        # Duplicate slot names within same class
        if ($seen_slot_names{$sname}++) {
            push @errors, "Class '$cname': duplicate slot '$sname'";
        }

        # Enum reference must resolve
        if ($slot->type eq 'enum') {
            unless ($model->has_enum($slot->enum)) {
                push @errors, "Class '$cname', slot '$sname': enum '" . $slot->enum . "' is not defined";
            } else {
                # If a default is set, it must be a valid enum value
                if (defined($slot->default)) {
                    my $enum = $model->enum($slot->enum);
                    unless ($enum->has_value($slot->default)) {
                        push @errors, "Class '$cname', slot '$sname': default '"
                            . $slot->default . "' is not a valid value for enum '"
                            . $slot->enum . "'";
                    }
                }
            }
        }

        # Autogenerated fields should not have a user-specified default
        if ($slot->autogenerated && defined($slot->default)) {
            push @errors, "Class '$cname', slot '$sname': autogenerated field should not have a default value (it is set by the database)";
        }

        # min/max make sense only for numeric types
        if (defined($slot->min) || defined($slot->max)) {
            unless (grep { $slot->type eq $_ } qw(integer float string)) {
                push @errors, "Class '$cname', slot '$sname': min/max are only valid for integer, float, or string types";
            }
        }

        # Pattern makes sense only for string-like types
        if (defined($slot->pattern)) {
            unless (grep { $slot->type eq $_ } qw(string text)) {
                push @errors, "Class '$cname', slot '$sname': pattern is only valid for string or text types";
            }
            # Try to compile the pattern
            eval { qr/${\$slot->pattern}/ };
            if ($@) {
                push @errors, "Class '$cname', slot '$sname': pattern '" . $slot->pattern . "' is not a valid regex: $@";
            }
        }
    }

    # Validate relationships
    for my $rel (@{$class->relationships}) {
        my $rname = $rel->name;

        # Target class must exist
        unless ($model->has_class($rel->target)) {
            push @errors, "Class '$cname', relationship '$rname': target class '"
                . $rel->target . "' is not defined";
            next;
        }

        # belongs_to: FK field must exist on this class
        if ($rel->is_belongs_to) {
            unless ($class->has_slot($rel->via)) {
                push @errors, "Class '$cname', relationship '$rname' (belongs_to): FK field '"
                    . $rel->via . "' does not exist on this class";
            }
        }

        # many_to_many: through class must exist
        if ($rel->is_many_to_many) {
            unless ($model->has_class($rel->through)) {
                push @errors, "Class '$cname', relationship '$rname' (many_to_many): through class '"
                    . $rel->through . "' is not defined";
            }
        }
    }

    # Validate constraints: all mentioned columns must exist in slots
    for my $con (@{$class->constraints}) {
        for my $col (@{$con->columns}) {
            unless ($class->has_slot($col)) {
                push @errors, "Class '$cname', constraint: column '$col' is not defined as a slot";
            }
        }
    }

    return @errors;
}

sub _check_inheritance_cycles {
    my ($self, $model) = @_;
    my @errors;

    for my $class ($model->classes) {
        next unless $class->has_parent;
        my %seen;
        my $current = $class;
        while ($current && $current->has_parent) {
            if ($seen{$current->name}++) {
                push @errors, "Inheritance cycle detected involving class '" . $class->name . "'";
                last;
            }
            $current = $model->class($current->is_a);
            last unless $current;
        }
    }

    return @errors;
}

1;

__END__

=head1 NAME

DataDriven::Framework::Schema::Validator - Validate a canonical Model's semantics

=head1 SYNOPSIS

    use DataDriven::Framework::Schema::Validator;

    my $validator = DataDriven::Framework::Schema::Validator->new;

    my @errors = $validator->validate($model);
    if (@errors) {
        die join("\n", @errors);
    }

    # Or die automatically:
    $validator->validate_or_die($model);

=head1 DESCRIPTION

Runs semantic validation checks on a L<DataDriven::Framework::Model>:

=over 4

=item * Parent classes exist

=item * Enum references resolve to defined enums

=item * Enum default values are valid members

=item * Autogenerated fields don't have explicit defaults

=item * Relationship targets exist

=item * belongs_to FK fields exist on the owning class

=item * many_to_many through classes exist

=item * Constraint columns are defined slots

=item * Regex patterns are valid

=item * No inheritance cycles

=back

=head1 METHODS

=over 4

=item C<validate($model)>

Returns a list of error strings. An empty list means the model is valid.

=item C<validate_or_die($model)>

Calls C<validate> and dies with all errors if any are found.

=back

=cut
