use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Model;
use DataDriven::Framework::Model::Class;
use DataDriven::Framework::Model::Slot;
use DataDriven::Framework::Model::Enum;
use DataDriven::Framework::Model::Relationship;
use DataDriven::Framework::Model::Constraint;
use DataDriven::Framework::Model::ValueType;

# ---- ValueType ----

ok(DataDriven::Framework::Model::ValueType->is_valid('string'),   'string is valid type');
ok(DataDriven::Framework::Model::ValueType->is_valid('integer'),  'integer is valid type');
ok(DataDriven::Framework::Model::ValueType->is_valid('enum'),     'enum is valid type');
ok(!DataDriven::Framework::Model::ValueType->is_valid('blob'),    'blob is invalid type');
is(DataDriven::Framework::Model::ValueType->mysql_type('string'),   'VARCHAR(255)', 'string -> VARCHAR(255)');
is(DataDriven::Framework::Model::ValueType->mysql_type('integer'),  'INT',          'integer -> INT');
is(DataDriven::Framework::Model::ValueType->mysql_type('boolean'),  'TINYINT(1)',   'boolean -> TINYINT(1)');
is(DataDriven::Framework::Model::ValueType->from_mysql_type('INT'), 'integer',      'INT -> integer');
is(DataDriven::Framework::Model::ValueType->from_mysql_type('VARCHAR(100)'), 'string', 'VARCHAR -> string');

# ---- Enum ----

my $enum = DataDriven::Framework::Model::Enum->new(
    name    => 'Status',
    values  => [qw(active inactive deleted)],
    default => 'active',
);
ok($enum, 'Enum created');
is($enum->name, 'Status', 'enum name');
is(scalar @{$enum->values}, 3, 'enum has 3 values');
ok($enum->has_value('active'),   'active is valid');
ok(!$enum->has_value('missing'), 'missing is invalid');
like($enum->mysql_enum_list, qr/'active'/, 'mysql enum list contains active');

# Bad default should die
eval {
    DataDriven::Framework::Model::Enum->new(
        name    => 'Bad',
        values  => [qw(a b)],
        default => 'c',
    );
};
ok($@, 'bad default dies');

# ---- Slot ----

my $slot = DataDriven::Framework::Model::Slot->new(
    name     => 'username',
    type     => 'string',
    required => 1,
    label    => 'Username',
    pattern  => '^[a-z]+$',
    ui_order => 2,
);
ok($slot, 'Slot created');
is($slot->name, 'username', 'slot name');
is($slot->type, 'string',   'slot type');
ok($slot->required,         'slot required');
is($slot->effective_label,  'Username', 'effective label from label');
ok(!$slot->is_nullable,     'required slot is not nullable');

my $auto_slot = DataDriven::Framework::Model::Slot->new(
    name          => 'id',
    type          => 'integer',
    autogenerated => 1,
    read_only     => 1,
    required      => 1,
);
ok($auto_slot->is_nullable == 0, 'autogenerated slot not nullable');
is($auto_slot->effective_control_type, 'number', 'integer control type is number');

# Auto-label generation
my $unlabeled = DataDriven::Framework::Model::Slot->new(name => 'device_class_id', type => 'integer');
is($unlabeled->effective_label, 'Device Class Id', 'auto-generated label from snake_case');

# Bad type
eval { DataDriven::Framework::Model::Slot->new(name => 'x', type => 'blob') };
ok($@, 'bad type dies');

# enum type without enum attribute
eval { DataDriven::Framework::Model::Slot->new(name => 'x', type => 'enum') };
ok($@, 'enum type without enum attr dies');

# ---- Constraint ----

my $uq = DataDriven::Framework::Model::Constraint->new(
    kind    => 'unique',
    columns => ['username'],
);
ok($uq->is_unique, 'is_unique');
ok(!$uq->is_index, 'not is_index');
like($uq->effective_name('users'), qr/uq_users_username/, 'effective name');
is($uq->column_list, '`username`', 'column list');

my $idx = DataDriven::Framework::Model::Constraint->new(
    kind    => 'index',
    columns => ['status', 'created_at'],
);
ok($idx->is_index, 'is_index');
like($idx->effective_name('posts'), qr/idx_posts_/, 'index effective name');

# ---- Relationship ----

my $bt = DataDriven::Framework::Model::Relationship->new(
    kind   => 'belongs_to',
    name   => 'user',
    target => 'User',
    via    => 'user_id',
);
ok($bt->is_belongs_to, 'is_belongs_to');
ok(!$bt->is_has_many,  'not is_has_many');

my $hm = DataDriven::Framework::Model::Relationship->new(
    kind   => 'has_many',
    name   => 'posts',
    target => 'Post',
);
ok($hm->is_has_many, 'is_has_many');

# ---- Class ----

my $class = DataDriven::Framework::Model::Class->new(
    name  => 'UserProfile',
    label => 'User Profile',
);
is($class->effective_label, 'User Profile', 'class label');
is($class->effective_table, 'user_profiles', 'auto table name');

$class->add_slot($slot);
ok($class->has_slot('username'), 'has_slot');
is($class->slot('username')->name, 'username', 'slot by name');

# Duplicate slot
eval { $class->add_slot($slot) };
ok($@, 'duplicate slot dies');

# ---- Model ----

my $model = DataDriven::Framework::Model->new(
    schema_version => '1.2.3',
    description    => 'Test model',
);
is($model->schema_version, '1.2.3', 'model schema version');

my $mc = DataDriven::Framework::Model::Class->new(name => 'TestClass', slots => []);
$model->add_class($mc);
ok($model->has_class('TestClass'), 'has_class');
is($model->class('TestClass')->name, 'TestClass', 'class by name');

my $me = DataDriven::Framework::Model::Enum->new(name => 'TestEnum', values => [qw(a b)]);
$model->add_enum($me);
ok($model->has_enum('TestEnum'), 'has_enum');

# Duplicate class
eval { $model->add_class($mc) };
ok($@, 'duplicate class dies');

my $hash = $model->model_hash;
ok(length($hash) == 32, 'model hash is 32 chars (md5)');

done_testing;
