use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use TestUtils qw(simple_schema_yaml);

my $parser = DataDriven::Framework::Schema::Parser->new;
ok($parser, 'Parser created');

# ---- Parse from YAML string ----

my $model = $parser->parse(simple_schema_yaml());
ok($model, 'Model parsed from YAML string');
isa_ok($model, 'DataDriven::Framework::Model');
is($model->schema_version, '1.0.0', 'schema version');
is($model->description, 'Simple test schema', 'description');

# Classes
ok($model->has_class('User'),  'has User class');
ok($model->has_class('Post'),  'has Post class');
ok($model->has_enum('Status'), 'has Status enum');

# User class
my $user = $model->class('User');
is($user->name, 'User', 'user name');
is($user->label, 'User', 'user label');
is($user->effective_table, 'users', 'user table');
ok(!$user->has_parent, 'User has no parent');
is(scalar @{$user->slots}, 5, 'User has 5 slots');

my $id_slot = $user->slot('id');
ok($id_slot, 'id slot exists');
is($id_slot->type, 'integer', 'id type');
ok($id_slot->autogenerated, 'id is autogenerated');
ok($id_slot->read_only, 'id is read_only');

my $status_slot = $user->slot('status');
ok($status_slot, 'status slot');
is($status_slot->type, 'enum', 'status type is enum');
is($status_slot->enum, 'Status', 'status enum name');
is($status_slot->default, 'active', 'status default');

my $username_slot = $user->slot('username');
is($username_slot->pattern, '^[a-z0-9_]+$', 'username pattern');

# User constraints
my @uq = $user->unique_constraints;
is(scalar @uq, 1, 'User has 1 unique constraint');
is($uq[0]->columns->[0], 'username', 'unique on username');

# Post class
my $post = $model->class('Post');
is(scalar @{$post->relationships}, 1, 'Post has 1 relationship');
my $rel = $post->relationships->[0];
is($rel->kind, 'belongs_to', 'belongs_to');
is($rel->target, 'User', 'target User');
is($rel->via, 'user_id', 'via user_id');

# Enum
my $enum = $model->enum('Status');
is(scalar @{$enum->values}, 3, 'Status has 3 values');
is($enum->default, 'active', 'Status default');

# ---- Parse from file ----

my $device_schema = TestUtils::device_schema_yaml();
SKIP: {
    skip "Device schema not found at $device_schema", 5 unless -f $device_schema;

    my $dmodel = $parser->parse($device_schema);
    ok($dmodel, 'Device model parsed from file');
    ok($dmodel->has_class('Device'),        'has Device');
    ok($dmodel->has_class('NetworkDevice'), 'has NetworkDevice');
    ok($dmodel->has_class('DeviceClass'),   'has DeviceClass');
    ok($dmodel->has_enum('DeviceStatus'),   'has DeviceStatus enum');
}

# ---- Parse errors ----

eval { $parser->parse('/nonexistent/file.yaml') };
ok($@, 'nonexistent file dies');

my $bad_schema = \<<'YAML';
schema_version: "1.0.0"
classes:
  Bad:
    slots:
      - name: missing_type
YAML
eval { $parser->parse($bad_schema) };
ok($@, 'slot without type dies');

done_testing;
