use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use DataDriven::Framework::Schema::Resolver;
use DataDriven::Framework::Schema::Validator;
use TestUtils qw(simple_schema_yaml);

my $parser    = DataDriven::Framework::Schema::Parser->new;
my $resolver  = DataDriven::Framework::Schema::Resolver->new;
my $validator = DataDriven::Framework::Schema::Validator->new;

sub parse_and_resolve {
    my ($yaml_ref) = @_;
    my $model = $parser->parse($yaml_ref);
    $resolver->resolve($model);
    return $model;
}

sub errors_for {
    my ($yaml_ref) = @_;
    my $model = eval { parse_and_resolve($yaml_ref) };
    return ("PARSE_ERROR: $@") if $@;
    return $validator->validate($model);
}

# ---- Valid schema ----

my $model = parse_and_resolve(simple_schema_yaml());
my @errors = $validator->validate($model);
is(scalar @errors, 0, 'simple schema has no validation errors');

# ---- validate_or_die ----

eval { $validator->validate_or_die($model) };
ok(!$@, 'validate_or_die does not die on valid schema');

# ---- Unknown enum reference ----

my @e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  Foo:
    slots:
      - name: x
        type: enum
        enum: NonExistentEnum
YAML
ok(grep { /NonExistentEnum/ } @e, 'error for unknown enum reference');

# ---- Unknown parent class ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  Child:
    is_a: NonExistentParent
    slots:
      - name: id
        type: integer
YAML
ok(grep { /parent class/ } @e, 'error for unknown parent class');

# ---- FK field missing ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  Owner:
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
  Owned:
    slots:
      - name: id
        type: integer
    relationships:
      belongs_to:
        - target: Owner
          via: owner_id
YAML
ok(grep { /owner_id.*does not exist/ } @e, 'error for missing FK field');

# ---- Constraint column missing ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  Foo:
    slots:
      - name: id
        type: integer
    constraints:
      unique: [nonexistent_col]
YAML
ok(grep { /nonexistent_col/ } @e, 'error for constraint on nonexistent column');

# ---- Bad enum default ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
enums:
  Color:
    values: [red, blue]
classes:
  Foo:
    slots:
      - name: color
        type: enum
        enum: Color
        default: green
YAML
ok(grep { /green.*not a valid/ } @e, 'error for bad enum default');

# ---- Bad regex pattern ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  Foo:
    slots:
      - name: code
        type: string
        pattern: '[invalid('
YAML
ok(grep { /not a valid regex/ } @e, 'error for invalid regex pattern');

# ---- Inheritance cycle detection ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  A:
    is_a: B
    slots:
      - name: id
        type: integer
  B:
    is_a: A
    slots:
      - name: id
        type: integer
YAML
ok(grep { /cycle/ } @e, 'error for inheritance cycle');

# ---- many_to_many through class missing ----

@e = errors_for(\<<'YAML');
schema_version: "1.0.0"
classes:
  Foo:
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
  Bar:
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
    relationships:
      many_to_many:
        - target: Foo
          through: FooBarJoin
YAML
ok(grep { /FooBarJoin/ } @e, 'error for missing through class');

done_testing;
