use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use DataDriven::Framework::Schema::Resolver;
use DataDriven::Framework::Schema::Validator;
use DataDriven::Framework::Generator::SQL;
use TestUtils qw(simple_schema_yaml);

sub build_model {
    my ($yaml_ref) = @_;
    my $parser    = DataDriven::Framework::Schema::Parser->new;
    my $resolver  = DataDriven::Framework::Schema::Resolver->new;
    my $validator = DataDriven::Framework::Schema::Validator->new;
    my $model = $parser->parse($yaml_ref);
    $resolver->resolve($model);
    $validator->validate_or_die($model);
    return $model;
}

my $model = build_model(simple_schema_yaml());
my $gen   = DataDriven::Framework::Generator::SQL->new(model => $model);
my $sql   = $gen->generate;

ok($sql, 'SQL generated');
like($sql, qr/CREATE TABLE/, 'contains CREATE TABLE');
like($sql, qr/_framework_schema_version/, 'contains framework metadata table');
like($sql, qr/_framework_migrations/, 'contains migrations table');
like($sql, qr/`users`/, 'contains users table');
like($sql, qr/`posts`/, 'contains posts table');
like($sql, qr/AUTO_INCREMENT/, 'contains AUTO_INCREMENT for PK');
like($sql, qr/NOT NULL/, 'contains NOT NULL constraints');
like($sql, qr/UNIQUE KEY/, 'contains UNIQUE KEY constraint');
like($sql, qr/FOREIGN KEY/, 'contains FOREIGN KEY');
like($sql, qr/VARCHAR\(255\)/, 'string type is VARCHAR(255)');
like($sql, qr/DATETIME/, 'datetime type is DATETIME');
like($sql, qr/ENUM\(/, 'enum type is ENUM');
like($sql, qr/'active'/, 'enum values in ENUM def');

# Check SET FOREIGN_KEY_CHECKS
like($sql, qr/SET FOREIGN_KEY_CHECKS = 0/, 'disables FK checks at top');

# Inheritance test
my $inh_model = build_model(\<<'YAML');
schema_version: "1.0.0"
classes:
  Animal:
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: name
        type: string
        required: true
  Dog:
    is_a: Animal
    slots:
      - name: breed
        type: string
YAML

my $inh_gen = DataDriven::Framework::Generator::SQL->new(model => $inh_model);
my $inh_sql = $inh_gen->generate;

like($inh_sql, qr/`animals`/, 'parent table animals created');
like($inh_sql, qr/`dogs`/, 'child table dogs created');
# Dog table should reference Animal FK
like($inh_sql, qr/REFERENCES `animals`/, 'dog FK references animals');

# Type max length
my $max_model = build_model(\<<'YAML');
schema_version: "1.0.0"
classes:
  Code:
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: code
        type: string
        max: 20
YAML

my $max_gen = DataDriven::Framework::Generator::SQL->new(model => $max_model);
my $max_sql = $max_gen->generate;
like($max_sql, qr/VARCHAR\(20\)/, 'string with max uses VARCHAR(max)');

# Deterministic output
my $sql2 = $gen->generate;
is($sql, $sql2, 'SQL generation is deterministic');

done_testing;
