use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use DataDriven::Framework::Schema::Resolver;
use DataDriven::Framework::Schema::Validator;
use DataDriven::Framework::Generator::OpenAPI;
use TestUtils qw(simple_schema_yaml);

sub build_model {
    my $parser   = DataDriven::Framework::Schema::Parser->new;
    my $resolver = DataDriven::Framework::Schema::Resolver->new;
    my $validator= DataDriven::Framework::Schema::Validator->new;
    my $model    = $parser->parse(simple_schema_yaml());
    $resolver->resolve($model);
    $validator->validate_or_die($model);
    return $model;
}

my $model = build_model();
my $gen   = DataDriven::Framework::Generator::OpenAPI->new(
    model       => $model,
    api_title   => 'Test API',
    api_version => '2.0.0',
    base_path   => '/api/v1',
);

my $spec = $gen->generate;
ok($spec, 'OpenAPI spec generated');
is($spec->{openapi}, '3.0.3', 'OpenAPI version');
is($spec->{info}{title}, 'Test API', 'API title');
is($spec->{info}{version}, '2.0.0', 'API version');

# Paths
ok(exists $spec->{paths}, 'has paths');
my $paths = $spec->{paths};
ok(exists $paths->{'/api/v1/users'}, 'has /api/v1/users path');
ok(exists $paths->{'/api/v1/users/{id}'}, 'has /api/v1/users/{id} path');
ok(exists $paths->{'/api/v1/posts'}, 'has /api/v1/posts path');

# Operations
my $user_list = $paths->{'/api/v1/users'};
ok(exists $user_list->{get},  'GET /users exists');
ok(exists $user_list->{post}, 'POST /users exists');

my $user_item = $paths->{'/api/v1/users/{id}'};
ok(exists $user_item->{get},    'GET /users/{id} exists');
ok(exists $user_item->{put},    'PUT /users/{id} exists');
ok(exists $user_item->{delete}, 'DELETE /users/{id} exists');

# Schemas
my $schemas = $spec->{components}{schemas};
ok(exists $schemas->{User}, 'User schema exists');
ok(exists $schemas->{UserInput}, 'UserInput schema exists');
ok(exists $schemas->{UserList},  'UserList schema exists');
ok(exists $schemas->{Status},    'Status enum schema exists');

# User schema has properties
my $user_schema = $schemas->{User};
is($user_schema->{type}, 'object', 'User is object type');
ok(exists $user_schema->{properties}{username}, 'User has username property');
ok(exists $user_schema->{properties}{status},   'User has status property');

# id should be readOnly in response schema
my $id_prop = $user_schema->{properties}{id};
ok($id_prop, 'id property in User schema');
is($id_prop->{readOnly}, 1, 'id is readOnly');

# UserInput should not have id (autogenerated)
my $input_schema = $schemas->{UserInput};
ok(!exists $input_schema->{properties}{id}, 'UserInput does not have id');
ok(exists $input_schema->{properties}{username}, 'UserInput has username');

# YAML output
my $yaml = $gen->generate_yaml;
ok($yaml, 'YAML output generated');
like($yaml, qr/openapi: 3\.0\.3/, 'YAML contains openapi version');
like($yaml, qr/Test API/, 'YAML contains title');

done_testing;
