use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use DataDriven::Framework::Schema::Resolver;
use DataDriven::Framework::Schema::Validator;
use DataDriven::Framework::Generator::JSONSchema;
use JSON::PP qw(decode_json);
use TestUtils qw(simple_schema_yaml);

sub build_model {
    my $parser   = DataDriven::Framework::Schema::Parser->new;
    my $resolver = DataDriven::Framework::Schema::Resolver->new;
    my $validator= DataDriven::Framework::Schema::Validator->new;
    my $model    = $parser->parse(simple_schema_yaml());
    $resolver->resolve($model);
    $validator->validate_or_die($model);
    return $model;
}

my $model = build_model();
my $gen   = DataDriven::Framework::Generator::JSONSchema->new(model => $model);

# Perl structure
my $schema = $gen->generate;
ok($schema, 'JSON Schema generated');
is($schema->{'$schema'}, 'http://json-schema.org/draft-07/schema#', 'draft-07');
ok(exists $schema->{definitions}, 'has definitions');
ok(exists $schema->{definitions}{User},   'User definition');
ok(exists $schema->{definitions}{Post},   'Post definition');
ok(exists $schema->{definitions}{Status}, 'Status enum definition');

# User definition
my $user_def = $schema->{definitions}{User};
is($user_def->{type}, 'object', 'User is object');
ok(exists $user_def->{properties}, 'User has properties');
my $props = $user_def->{properties};

ok(exists $props->{username}, 'has username');
is($props->{username}{type}, 'string', 'username is string');
like($props->{username}{pattern}, qr/a-z/, 'username has pattern');

ok(exists $props->{id}, 'has id');
# readOnly should be set for autogenerated
ok($props->{id}{readOnly}, 'id is readOnly');

# Status enum in properties
ok(exists $props->{status}, 'has status');
ok(exists $props->{status}{enum}, 'status has enum values');
is(scalar @{$props->{status}{enum}}, 3, 'status has 3 enum values');

# Required
ok(exists $user_def->{required}, 'User has required array');
my %req = map { $_ => 1 } @{$user_def->{required}};
ok($req{username}, 'username is required');
ok($req{email}, 'email is required');
ok(!$req{id}, 'id (autogenerated) is not in required');

# max constraint
my $post_def = $schema->{definitions}{Post};
ok(exists $post_def->{properties}{title}{maxLength}, 'title has maxLength');
is($post_def->{properties}{title}{maxLength}, 255, 'title maxLength is 255');

# JSON output
my $json = $gen->generate_json;
ok($json, 'JSON output');
my $parsed = decode_json($json);
ok($parsed->{'$schema'}, 'Parsed JSON has $schema');
ok($parsed->{definitions}{User}, 'Parsed JSON has User definition');

# additionalProperties
is($user_def->{additionalProperties}, 0, 'additionalProperties is false');

done_testing;
