use strict;
use warnings;
use Test::More;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use DataDriven::Framework::Schema::Resolver;
use DataDriven::Framework::Schema::Validator;
use DataDriven::Framework::Diff::SchemaComparator;
use DataDriven::Framework::Generator::Migration;

sub build_model {
    my ($yaml_ref) = @_;
    my $parser    = DataDriven::Framework::Schema::Parser->new;
    my $resolver  = DataDriven::Framework::Schema::Resolver->new;
    my $validator = DataDriven::Framework::Schema::Validator->new;
    my $model     = $parser->parse($yaml_ref);
    $resolver->resolve($model);
    $validator->validate_or_die($model);
    return $model;
}

my $v1 = build_model(\<<'YAML');
schema_version: "1.0.0"
classes:
  Widget:
    table: widgets
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: name
        type: string
        required: true
      - name: color
        type: string
    constraints:
      unique: [name]
YAML

my $v2 = build_model(\<<'YAML');
schema_version: "1.1.0"
classes:
  Widget:
    table: widgets
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: name
        type: string
        required: true
      - name: size
        type: integer
    constraints:
      unique: [name]

  Gadget:
    table: gadgets
    slots:
      - name: id
        type: integer
        autogenerated: true
        read_only: true
        required: true
      - name: label
        type: string
        required: true
YAML

my $cmp = DataDriven::Framework::Diff::SchemaComparator->new(
    from_model => $v1,
    to_model   => $v2,
);

my @ops = $cmp->diff;
ok(scalar @ops > 0, 'diff has operations');

my @op_types = map { $_->{op} } @ops;

ok((grep { $_->{op} eq 'add_column' } @ops), 'has add_column op');

ok((grep { $_->{op} eq 'drop_column' } @ops), 'has drop_column op');
ok((grep { $_->{op} eq 'create_table' } @ops), 'has create_table op for Gadget');

# Check warning on destructive op
my ($drop) = grep { $_->{op} eq 'drop_column' } @ops;
ok($drop->{warning}, 'drop_column has warning');

# Migration SQL
my $migrator = DataDriven::Framework::Generator::Migration->new(
    from_model => $v1,
    to_model   => $v2,
);

my $sql = $migrator->generate_sql;
ok($sql, 'migration SQL generated');
like($sql, qr/1\.0\.0.*->.*1\.1\.0|1\.0\.0 -> 1\.1\.0/, 'SQL mentions version change');
like($sql, qr/ALTER TABLE/, 'SQL contains ALTER TABLE');
like($sql, qr/WARNING/, 'SQL contains WARNING for destructive op');
like($sql, qr/CREATE TABLE.*gadgets|gadgets.*CREATE TABLE/, 'SQL creates gadgets table');

# Migration summary
my $summary = $migrator->generate_summary;
ok($summary, 'migration summary generated');
like($summary, qr/Migration Summary/, 'summary has heading');
like($summary, qr/New Tables|Dropped|Added|Modified/, 'summary has sections');

# No-change migration
my $same_migrator = DataDriven::Framework::Generator::Migration->new(
    from_model => $v1,
    to_model   => $v1,
);
my $same_sql = $same_migrator->generate_sql;
is($same_sql, '', 'no-change migration produces empty SQL');

my $same_summary = $same_migrator->generate_summary;
like($same_summary, qr/No changes detected/, 'no-change summary says no changes');

done_testing;
