use strict;
use warnings;
use Test::More;
use File::Temp qw(tempdir);
use File::Spec;
use FindBin qw($Bin);
use lib "$Bin/../lib", "$Bin/lib";

use DataDriven::Framework::Schema::Parser;
use DataDriven::Framework::Schema::Resolver;
use DataDriven::Framework::Schema::Validator;
use DataDriven::Framework::Generator::UI;
use JSON::PP qw(decode_json);
use TestUtils qw(simple_schema_yaml);

sub build_model {
    my $parser   = DataDriven::Framework::Schema::Parser->new;
    my $resolver = DataDriven::Framework::Schema::Resolver->new;
    my $validator= DataDriven::Framework::Schema::Validator->new;
    my $model    = $parser->parse(simple_schema_yaml());
    $resolver->resolve($model);
    $validator->validate_or_die($model);
    return $model;
}

my $model  = build_model();
my $outdir = tempdir(CLEANUP => 1);

my $gen = DataDriven::Framework::Generator::UI->new(
    model      => $model,
    output_dir => $outdir,
);

my @files = $gen->generate;
ok(scalar @files > 0, 'UI files generated');

# JSON config for User
my $user_json = File::Spec->catfile($outdir, 'user_ui.json');
ok(-f $user_json, 'user_ui.json created');

open my $fh, '<', $user_json or die $!;
my $json_text = do { local $/; <$fh> };
close $fh;

my $config = decode_json($json_text);
ok($config, 'user_ui.json parsed');
is($config->{class}, 'User', 'config class is User');
is($config->{label}, 'User', 'config label is User');
ok(exists $config->{list},  'has list config');
ok(exists $config->{form},  'has form config');

# List columns
my @list_cols = @{$config->{list}{columns}};
ok(@list_cols > 0, 'has list columns');
my %col_by_field = map { $_->{field} => $_ } @list_cols;
ok(exists $col_by_field{username}, 'username in list columns');
ok(!exists $col_by_field{id} || $col_by_field{id},
   'id may be in list (it is visible)');

# Form groups
my @groups = @{$config->{form}{groups}};
ok(@groups > 0, 'has form groups');
my @all_form_fields = map { @{$_->{fields}} } @groups;
my %form_by_name = map { $_->{name} => $_ } @all_form_fields;
ok(exists $form_by_name{username}, 'username in form fields');
ok(!exists $form_by_name{id}, 'id (autogenerated) not in form');
ok(!exists $form_by_name{created_at}, 'created_at (read_only) not in form');

# status field should have options (enum)
ok(exists $form_by_name{status}, 'status in form fields');
ok(exists $form_by_name{status}{options}, 'status has options');
ok(scalar @{$form_by_name{status}{options}} == 3, 'status has 3 options');

# HTML for User
my $user_html = File::Spec->catfile($outdir, 'user.html');
ok(-f $user_html, 'user.html created');

open $fh, '<', $user_html or die $!;
my $html = do { local $/; <$fh> };
close $fh;

like($html, qr/<!DOCTYPE html>/, 'valid HTML doctype');
like($html, qr/### BEGIN GENERATED ###/, 'has begin marker');
like($html, qr/### END GENERATED ###/, 'has end marker');
like($html, qr/<table/, 'has list table');
like($html, qr/<form/, 'has form');
like($html, qr/type="text".*name="username"|name="username".*type="text"/, 'username text input');
like($html, qr/<select.*status|status.*<select/, 'status select input');

# HTML regeneration preserves custom content
open $fh, '>>', $user_html or die $!;
print $fh "\n<!-- Custom footer content -->\n";
close $fh;

$gen->generate;

open $fh, '<', $user_html or die $!;
my $regen = do { local $/; <$fh> };
close $fh;

like($regen, qr/Custom footer content/, 'custom content preserved');
like($regen, qr/### BEGIN GENERATED ###/, 'generated markers still present');

done_testing;
